### ISSUE TITLE
Uncaught TypeError: Cannot read property 'folders' of null

### ISSUE THREAD

**Issue by grenierdev** [mgrenier/remote-ftp#1]
- Downloaded a whole website
- Edited & save a local file (not through the remote)

```
Uncaught TypeError: Cannot read property 'folders' of null d:\Users\Michael\.atom\packages\remote-ftp\lib\views\directory-view.js:107
```

**Comment by dantman** [comment]
Why is this closed? I get this error every time I try renaming a folder and then I have to restart Atom to fix it.

**Comment by JamesCoyle** [comment]
Still requires a restart or <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>R</kbd> to show the renamed folder and remove the error message.

**Comment by pruge** [comment]
quick fix

lib/directory-view.js

```
114  self.item.folders.forEach(function (item) {
   ->  self.item && self.item.folders.forEach(function (item) {

122 self.item.files.forEach(function (item) {
  ->  self.item && self.item.files.forEach(function (item) {
```

**Comment by umren** [comment]
not fixed, get this error for 6 months now
