### ISSUE TITLE
autodownload?

### ISSUE THREAD

**Issue by joantp** [mgrenier/remote-ftp#1342]
I haven't been able to find a way of autodownloading on opening a file? It auto-uploads on save, but I'd like automatic remote->local on opening file.

Thank you!

**Comment by icetee** [comment]
It would be dangerous. Right now, the only way I think is double-click the remote tree file. It downloads and opens when you have open reloads.

**Comment by icetee** [comment]
Unfortunately, it’s also old about text-based technology. It is not possible to indicate whether the content has been modified by examining the contents of the files. There is a checksum, but it must be enabled separately on the server, so it's like it doesn't exist. However, if you work on, say, multiple machines, or with others, you will smoothly lose data.
