### ISSUE TITLE
Administrator permissions

### ISSUE THREAD

**Issue by 42willow** [mgrenier/remote-ftp#1393]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description
When I try to create a file (in a folder which requires administrator privileges it doesn't work. Is there a way to get administrator permissions? I am using a Raspberry Pi as the host.

### Steps to Reproduce
1. Try to create a file which requires administrator permissions
2. It doesn't create the file

**Expected behavior:** [What you expect to happen]
The file to be created.

**Actual behavior:** [What actually happens]
The file isn't created.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
Atom: 1.60.0
Electron: 9.4.4
Chrome: 83.0.4103.122
Node : 12.14.1
OS: Windows 11 21H2

**Comment by bjhaneline21291** [comment]
> ### Prerequisites
> * [x]  Put an X between the brackets on this line if you have done all of the following:
>   
>   * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues
> 
> ### Description
> When I try to create a file (in a folder which requires administrator privileges it doesn't work. Is there a way to get administrator permissions? I am using a Raspberry Pi as the host.
> 
> ### Steps to Reproduce
> 1. Try to create a file which requires administrator permissions
> 2. It doesn't create the file
> 
> **Expected behavior:** [What you expect to happen] The file to be created.
> 
> **Actual behavior:** [What actually happens] The file isn't created.
> 
> **Reproduces how often:** [What percentage of the time does it reproduce?] 100%
> 
> ### Versions
> Atom: 1.60.0 Electron: 9.4.4 Chrome: 83.0.4103.122 Node : 12.14.1 OS: Windows 11 21H2

**Comment by bjhaneline21291** [comment]
@bjhaneline21291 #463 [](_1OkiPyJjXuVYQYFFABXk8A)

**Comment by 42willow** [comment]
Atom.io has been deprecated. Maybe archive this repository?
