### ISSUE TITLE
Install failing on Apple M1

### ISSUE THREAD

**Issue by MarScheff** [mgrenier/remote-ftp#1394]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

Can't install on an Mac Book Pro 2021 M1

Fails with the following message:
17 verbose node v12.14.1
18 verbose npm  v6.14.13
19 error code E500
20 error 500 Internal Server Error - GET https://www.atom.io/api/packages/remote-ftp/versions/2.2.4/tarball
21 verbose exit [ 1, true ]

### Steps to Reproduce

1. Plain Install of ATOM
2. Try to install from Package Manager ==> Fails after a few minutes
3. Try to install from Repository vi click ==> Fails after a few minutes
4. Try to download tar via Browser and WGET: https://www.atom.io/api/packages/remote-ftp/versions/2.2.4/tarball

**Expected behavior:** 
Clean Install
**Actual behavior:** 
Fails
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions
1.60.0

### Additional Information

Also the automated Update of Atom fails at the moment

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
1 verbose cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/Users/username/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/Users/username/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/remote-ftp/versions/2.2.4/tarball',
1 verbose cli   '--target=9.4.4',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v12.14.1
4 verbose npm-session 105d78bdf01582ac
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 500 https://www.atom.io/api/packages/remote-ftp/versions/2.2.4/tarball 110857ms attempt #3
8 silly fetchPackageMetaData error for https://www.atom.io/api/packages/remote-ftp/versions/2.2.4/tarball 500 Internal Server Error - GET https://www.atom.io/api/packages/remote-ftp/versions/2.2.4/tarball
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 110902ms
11 verbose stack Error: 500 Internal Server Error - GET https://www.atom.io/api/packages/remote-ftp/versions/2.2.4/tarball
11 verbose stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:117:15
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:94:5)
12 verbose statusCode 500
13 verbose pkgid https://www.atom.io/api/packages/remote-ftp/versions/2.2.4/tarball
14 verbose cwd /private/var/folders/9m/1svsbyx13b55ghwvt_tb6t6r0000gn/T/apm-install-dir-2022320-23605-ql63zf.x4ofd
15 verbose Darwin 21.4.0
16 verbose argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/username/.atom/.apm/.apmrc" "--userconfig" "/Users/username/.atom/.apmrc" "install" "https://www.atom.io/api/packages/remote-ftp/versions/2.2.4/tarball" "--target=9.4.4" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
17 verbose node v12.14.1
18 verbose npm  v6.14.13
19 error code E500
20 error 500 Internal Server Error - GET https://www.atom.io/api/packages/remote-ftp/versions/2.2.4/tarball
21 verbose exit [ 1, true ]

**Comment by icetee** [comment]
I think is a server error. Maybe related this https://github.com/atom/atom/issues/25417?

**Comment by MarScheff** [comment]
Yes, that was the problem. Does now work like a charm. Thanks for the good work ...
